Class CDV.Utils Extends %Persistent
{

Storage Default
{
<Data name="UtilsDefaultData">
<Value name="1">
<Value>%%CLASSNAME</Value>
</Value>
</Data>
<DataLocation>^CDV.UtilsD</DataLocation>
<DefaultData>UtilsDefaultData</DefaultData>
<IdLocation>^CDV.UtilsD</IdLocation>
<IndexLocation>^CDV.UtilsI</IndexLocation>
<StreamLocation>^CDV.UtilsS</StreamLocation>
<Type>%Library.CacheStorage</Type>
}

}

